name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install i386 library
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6-dev-i386
    
    - name: Install dependencies
      run: make
